package pharmacymanagementsystem;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.MouseAdapter;
import javax.swing.*;
import java.util.HashMap;
import org.w3c.dom.events.Event;
import org.w3c.dom.events.MouseEvent;

/**
 *
 * @author Saoudi Massinissa
 */
public class Agents extends javax.swing.JFrame {
    static Connection DBconnect(){
    Connection conn= null;
    String DB_URL = "jdbc:postgresql://localhost:5433/PharmaDB";
    String USER = "postgres";
    String PASS = "admin";
    try{
         conn = DriverManager.getConnection(DB_URL, USER, PASS); 
         
    }catch(Exception e){
        System.out.println(e.getMessage());
    }
     return conn;
    }
    /**
     * Creates new form Agents
     */
    public Agents() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void initComponents() {

        gen_container = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        agent_id_label = new javax.swing.JLabel();
        login_label = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();
        function_label = new javax.swing.JLabel();
        pwd_label = new javax.swing.JLabel();
        phone_label = new javax.swing.JLabel();
        add_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        update_btn.addMouseListener(new MouseAdapter() {
            public void mouseClicked (MouseEvent e) {

                System.out.println("jhjgjg");
                String name = name_field.getText();
                Object function = functionComboBox.getSelectedItem();
                String password = pwd_field.getText();
                String login = login_field.getText();
                String phone = phone_field.getText();
                String id = agent_id_field.getText();
                try{
                    Connection cnx = DBconnect();
                    Statement stmt = cnx.createStatement();
                    stmt.executeUpdate("UPDATE agents set name='"+name+"',function='"+function+"',phone='"+phone+"',pwd='"+password+"',login='"+login+"'WHERE agentid = "+id+";");
                }
                catch(Exception err){
                    System.out.println(err.getMessage());
                }
            }
        });

        delete_btn = new javax.swing.JButton();
        functionComboBox = new javax.swing.JComboBox<>();
        agent_id_field = new javax.swing.JTextField();
        name_field = new javax.swing.JTextField();
        login_field = new javax.swing.JTextField();
        pwd_field = new javax.swing.JTextField();
        phone_field = new javax.swing.JTextField();
        table_container = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AgentsTable = new  javax.swing.JTable();
        AgentsTable.addMouseListener(new MouseAdapter() {
            public void mouseClicked (MouseEvent e) {
              int row = AgentsTable.getSelectedRow();

            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 0));
        setMinimumSize(null);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 500));

        gen_container.setBackground(new java.awt.Color(51, 153, 0));
        gen_container.setForeground(new java.awt.Color(255, 255, 255));
        gen_container.setName("Container"); // NOI18N

        logo.setBackground(new java.awt.Color(255, 255, 255));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacymanagementsystem/2.png"))); // NOI18N

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.setText("Agents Management");

        container.setBackground(new java.awt.Color(255, 255, 255));

        agent_id_label.setBackground(new java.awt.Color(255, 255, 255));
        agent_id_label.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        agent_id_label.setForeground(new java.awt.Color(51, 153, 0));
        agent_id_label.setText("AgentID");

        login_label.setBackground(new java.awt.Color(255, 255, 255));
        login_label.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        login_label.setForeground(new java.awt.Color(51, 153, 0));
        login_label.setText("Login");

        name_label.setBackground(new java.awt.Color(255, 255, 255));
        name_label.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        name_label.setForeground(new java.awt.Color(51, 153, 0));
        name_label.setText("Name");

        function_label.setBackground(new java.awt.Color(255, 255, 255));
        function_label.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        function_label.setForeground(new java.awt.Color(51, 153, 0));
        function_label.setText("Function");

        pwd_label.setBackground(new java.awt.Color(255, 255, 255));
        pwd_label.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        pwd_label.setForeground(new java.awt.Color(51, 153, 0));
        pwd_label.setText("Password");

        phone_label.setBackground(new java.awt.Color(255, 255, 255));
        phone_label.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        phone_label.setForeground(new java.awt.Color(51, 153, 0));
        phone_label.setText("Phone");

        add_btn.setBackground(new java.awt.Color(51, 153, 0));
        add_btn.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        add_btn.setForeground(new java.awt.Color(255, 255, 255));
        add_btn.setText("Add");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        clear_btn.setBackground(new java.awt.Color(51, 153, 0));
        clear_btn.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        clear_btn.setForeground(new java.awt.Color(255, 255, 255));
        clear_btn.setText("Clear");

        update_btn.setBackground(new java.awt.Color(51, 153, 0));
        update_btn.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        update_btn.setForeground(new java.awt.Color(255, 255, 255));
        update_btn.setText("Update");

        delete_btn.setBackground(new java.awt.Color(51, 153, 0));
        delete_btn.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(255, 255, 255));
        delete_btn.setText("Delete");

        functionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        agent_id_field.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N

        name_field.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N

        login_field.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N

        pwd_field.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N

        phone_field.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(add_btn)
                        .addGap(89, 89, 89)
                        .addComponent(clear_btn)
                        .addGap(101, 101, 101)
                        .addComponent(update_btn)
                        .addGap(110, 110, 110)
                        .addComponent(delete_btn))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(function_label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agent_id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(agent_id_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(name_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(functionComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(containerLayout.createSequentialGroup()
                                .addComponent(pwd_label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pwd_field, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(containerLayout.createSequentialGroup()
                                .addComponent(login_label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(login_field, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(containerLayout.createSequentialGroup()
                                .addComponent(phone_label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(phone_field, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agent_id_label)
                    .addComponent(login_label)
                    .addComponent(agent_id_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_label)
                    .addComponent(pwd_label)
                    .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwd_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(function_label)
                    .addComponent(phone_label)
                    .addComponent(functionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_btn)
                    .addComponent(update_btn)
                    .addComponent(clear_btn)
                    .addComponent(delete_btn))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        table_container.setBackground(java.awt.Color.lightGray);

        AgentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "AgentID", "Name", "Function", "Login", "Password", "Phone"
            }
        ));

        jScrollPane1.setViewportView(AgentsTable);
        try{

            HashMap allAgents = GetAgents();
            System.out.println(allAgents.getClass());
            // for (Object i : allAgents.keySet()){
            //     System.out.println(i);
            // }
            for(Object i : allAgents.values()){
                Object[] v = (Object[]) i;
                insertintotable(v);
            }

                    }catch(Exception e){
                        System.err.println(e.getMessage());
                    }
        javax.swing.GroupLayout table_containerLayout = new javax.swing.GroupLayout(table_container);
        table_container.setLayout(table_containerLayout);
        table_containerLayout.setHorizontalGroup(
            table_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
        );
        table_containerLayout.setVerticalGroup(
            table_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table_containerLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout gen_containerLayout = new javax.swing.GroupLayout(gen_container);
        gen_container.setLayout(gen_containerLayout);
        gen_containerLayout.setHorizontalGroup(
            gen_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gen_containerLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(gen_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gen_containerLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gen_containerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gen_containerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(table_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gen_containerLayout.setVerticalGroup(
            gen_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gen_containerLayout.createSequentialGroup()
                .addGroup(gen_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gen_containerLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(gen_containerLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(table_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gen_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gen_container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        AgentsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = AgentsTable.rowAtPoint(evt.getPoint());
                int column_numbers = AgentsTable.getColumnCount();
         if(row>=0){
            String agentid= String.valueOf(AgentsTable.getValueAt(row, 0));
            agent_id_field.setText(agentid);
            agent_id_field.setEditable(false);
            add_btn.setEnabled(false);
            String name= String.valueOf(AgentsTable.getValueAt(row, 1));
            name_field.setText(name);
            String function= String.valueOf(AgentsTable.getValueAt(row, 2));

            functionComboBox.setSelectedItem(function);
            String login= String.valueOf(AgentsTable.getValueAt(row, 3));
            login_field.setText(login);
            String password= String.valueOf(AgentsTable.getValueAt(row, 4));
            pwd_field.setText(password);
            String phone= String.valueOf(AgentsTable.getValueAt(row, 5));
            phone_field.setText(phone);
         }
            }
        });
    }// </editor-fold>//GEN-END:initComponents
public void insertintotable(Object[] row){
  try{
    DefaultTableModel tm =  (DefaultTableModel) AgentsTable.getModel();
    tm.addRow(row);
  }catch(Exception e){System.out.println(e.getMessage());}
   
    
}
////////////
///GETTING THE DATA
////////////
public HashMap GetAgents(){
HashMap<String,Object[]> allData = new HashMap<String, Object[]>();
try{
Connection conn = DBconnect();
Statement stmt = conn.createStatement();
ResultSet all_rows = stmt.executeQuery("select * from agents"); 
    
while(all_rows.next()){
                Object[] value = {all_rows.getString("agentid"),all_rows.getString("name"),all_rows.getString("function"),all_rows.getString("login"),all_rows.getString("pwd"),all_rows.getString("phone")};
                String key = all_rows.getString("agentid");
                allData.put(key, value);
            }
}
catch(Exception e){
    System.out.println(e.getMessage());
}
return allData;
}

private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {                                           
    String name = name_field.getText();
    Object function = functionComboBox.getSelectedItem();
    String password = pwd_field.getText();
    String login = login_field.getText();
    String phone = phone_field.getText();
    String id = agent_id_field.getText();
    try{
        Connection cnx = DBconnect();
        Statement stmt = cnx.createStatement();
        stmt.executeUpdate("UPDATE agents set name='"+name+"',function='"+function+"',phone='"+phone+"',pwd='"+password+"',login='"+login+"'WHERE agentid = '"+id+"';");
    }
    catch(Exception e){
        System.out.println(e.getMessage());
    }
    
}   
    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        String agent_id=agent_id_field.getText();String login=login_field.getText();String name=name_field.getText();
        String pwd=pwd_field.getText();String phone=phone_field.getText();Object function=functionComboBox.getSelectedItem();
        //System.out.println("insert into agents values('"+agent_id+"','"+name+"','"+function+"','"+pwd+"','"+phone+"','"+login+"');");
        

        
        Connection conn = DBconnect();
       try{
            Statement stmt = conn.createStatement();
            String sql = "insert into agents values('"+agent_id+"','"+name+"','"+function+"','"+pwd+"','"+phone+"','"+login+"');";
            stmt.execute(sql);
       DefaultTableModel tm =  (DefaultTableModel) AgentsTable.getModel();
       System.out.println(tm.getRowCount());
       tm.addRow(new Object[]{agent_id, name, function, login,pwd, phone });
       System.out.println(tm.getRowCount());
       System.out.println(AgentsTable.getRowCount());
       }catch(Exception e){
           System.out.println(e.getMessage());
       }
    }//GEN-LAST:event_add_btnActionPerformed

    /**
     * @param args the command line arguments
     */
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTable AgentsTable;
    private javax.swing.JButton add_btn;
    private javax.swing.JTextField agent_id_field;
    private javax.swing.JLabel agent_id_label;
    private javax.swing.JButton clear_btn;
    private javax.swing.JPanel container;
    private javax.swing.JButton delete_btn;
    private javax.swing.JComboBox<String> functionComboBox;
    private javax.swing.JLabel function_label;
    private javax.swing.JPanel gen_container;
    private javax.swing.JLabel header;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField login_field;
    private javax.swing.JLabel login_label;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField name_field;
    private javax.swing.JLabel name_label;
    private javax.swing.JTextField phone_field;
    private javax.swing.JLabel phone_label;
    private javax.swing.JTextField pwd_field;
    private javax.swing.JLabel pwd_label;
    private javax.swing.JPanel table_container;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
